version: "3"
services:
  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis_schedule
    ports:
      - "6379:6379"
    networks:
      schedule_network:
        ipv4_address: 172.16.238.2
networks:
  schedule_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24